export const fontFamilies = [
  "VAGRoundedLTCYR",
  "Tactic Round Bld",
  "Tactic Round Blk It",
  "Tactic Round Blk It",
  "Tactic Round  Ult It",
  "TT Rounds Neue",
  "PFBagueRoundPro",
  "SF Pro Mistu Rounded",
  "Sofia Sans",
  "Open Runde",
  "Comfortaa",
  "Rounded Mplus 1c",
  "VAG Round Cyrilic",
  "Rounded",
  "CQ Mono",
  "RussianRail G Pro",
  "CPMono_v07",
  "CroogPro",
  "Designosaur",
  "Polly Rounded",
  "18VAG Rounded M",
  "AdobeCleanUI",
  "Duepontozero Pro",
  "Visby Round CF",
  "Source Code Pro",
  "Ubuntu Mono",
  "Inter VariableText",
  "HarmonyOS Sans ",
  "Luculent 11",
  "Maple Mono",
  "Marta",
  "NeoSansProCyr",
  "NotoSansM NFM",
  "OverpassNFP",
  "Polly Rounded ",
  "Prosto One",
  "RF Dewi",
  "Rounded Mplus 1c ",
  "RussianRailGPro",
  "Segoe UI ",
  "Stage Wander",
  "Rounded Regular",
  "MartianMono NFM Med",
  "MegaFonts Inc",
  "Microsoft JhengHei",
  "Microsoft YaHei UI",
  "Microsoft Yi Baiti",
  "UbuntuSansMono NFi",
  "Ubuntu Mono ",
  "Ubuntu Medium",
  "UbuntuSans NF ",
  "VAG Round Cyrillic",
  "VisbyRoundCF",
  "Volte Rounded ",
  "ZedMono NFP Extra",
  "PFBagueRoundPro",
  "VAGRoundedLTCYR",
  "MonaspiceNeNFM",
  "MonaspiceRnNFP",
  "monofur    for Powerline",
  "JetBrainsMonoNL",
  "SF Pro Mistu Rounded",
  "SF UI Display ",
  "SF UI Text ",
  "SFProRounded",
  "SFProRounded",
  "InconsolataForPowerline",
  "CoreSansDS65",
  "CoreSansDS75",
  "BwSurco",
  "BloggerSans",
  "BlexMono Nerd Font Mono ",
  "BlexMono Nerd Font",
  "Intel One Mono ",
  "JetBrainsMonoNL NF ",
  "Iosevka Semi Extended",
  "DuepuntozeroPro",
  "Segoe UI VariableText",
  "Inter Variable Text",
  "Segoe UI  Variable Display",
  "Source Code Variable",
  "Sofia Sans",
  "Sofia Sans",
  "SFProDisplay",
  "SFProText-Heavy",
  "SFProDisplay",
  "SFProText-Heavy",
  "SF Pro Display",
  "SF Mono",
  "SF Pro Rounded",
  "SF UI Display",
  "SF Pro Text",
  "SF UI Text",
  "SF Pro Mistu Rounded",
];
