export const fontFamilies = [
  "0xProto Nerd Font",
  "0xProto Nerd Font Mono",
  "0xProto Nerd Font Propo",
  "18VAG Rounded M",
  "3270 Nerd Font",
  "3270 Nerd Font Mono",
  "Adobe Clean UI",
  "Aharoni",
  "Amstelvar",
  "Angsana New",
  "AngsanaUPC",
  "Anka/Coder",
  "Anonymous Pro for Powerline",
  "Arciform Sans cyr-lat",
  "Arial",
  "Arial Nova",
  "Arial Rounded MT Pro Cyr",
  "Arimo for Powerline",
  "Arturito Slab",
  "AurulentSansM Nerd Font",
  "AurulentSansM Nerd Font Mono",
  "AurulentSansM Nerd Font Propo",
  "B612 Mono",
  "BIZ UDGothic",
  "BIZ UDMincho",
  "BIZ UDPGothic",
  "BIZ UDPMincho",
  "Bahnschrift",
  "Basis Grotesque Pro",
  "BitstromWera Nerd Font",
  "BitstromWera Nerd Font Mono",
  "BitstromWera Nerd Font Propo",
  "BlexMono Nerd Font",
  "BlexMono Nerd Font Mono",
  "BlexMono Nerd Font Propo",
  "Blogger Sans",
  "Bounded",
  "Browallia New",
  "BrowalliaUPC",
  "Bw Surco",
  "CPMono_v07",
  "CPMono_v07 Plain",
  "CQ Mono [RUS by Daymarius]",
  "CTC Splash Rounded",
  "Calibri",
  "Cambria",
  "Cambria Math",
  "Candara",
  "Cascadia Code",
  "Cascadia Code PL",
  "Cascadia Mono",
  "Cascadia Mono PL",
  "Coiny Cyrillic",
  "Comfortaa",
  "Comic Sans MS",
  "Connie",
  "Consolas",
  "Consolate Elf",
  "Constantia",
  "Convection",
  "Corbel",
  "Cordia New",
  "CordiaUPC",
  "Core Sans DS",
  "Core Sans DS 15",
  "Core Sans DS 35",
  "Core Sans DS 45",
  "Core Sans DS 55",
  "Courier New",
  "Cousine for Powerline",
  "Croog Pro",
  "DELL CYR [Rus by me]",
  "DINPro",
  "DaunPenh",
  "David",
  "DejaVu Sans Mono for Powerline",
  "DengXian",
  "DepartureMono Nerd Font",
  "DepartureMono Nerd Font Mono",
  "DepartureMono Nerd Font Propo",
  "Designosaur",
  "Devicons Nerd Font NerdFont",
  "DigitizedArtistik",
  "DilleniaUPC",
  "DokChampa",
  "Droid Sans Mono Dotted for Powerline",
  "Droid Sans Mono Slashed for Powerline",
  "Droid Sans Mono for Powerline",
  "Duepuntozero Pro",
  "Duepuntozero Pro Icon",
  "Ebrima",
  "EffectsEighty",
  "EffectsEighty BoldItalic",
  "Espresso Mono",
  "Estrangelo Edessa",
  "EucrosiaUPC",
  "Euphemia",
  "Eurostile Round",
  "FA Nerd Font NerdFont",
  "FangSong",
  "Fantasque Sans Mono",
  "FantasqueSansM Nerd Font",
  "FantasqueSansM Nerd Font Mono",
  "FantasqueSansM Nerd Font Propo",
  "Filson Pro",
  "Fira Code",
  "Fira Code Retina",
  "Fira Mono for Powerline",
  "FiraFlott",
  "FlashRomanBold_DG",
  "Fog Sans",
  "Fog Sans It",
  "Fog Sans Outline",
  "Fog Sans OutlineIt",
  "FrankRuehl",
  "Franklin Gothic",
  "Franxurter Totally",
  "Franxurter Totally Fat",
  "Fredoka One",
  "FreesiaUPC",
  "Gabriola",
  "Gadugi",
  "Gals",
  "Gautami",
  "Georgia",
  "Georgia Pro",
  "Gill Sans Nova",
  "Gisha",
  "Go Mono for Powerline",
  "Goldplay",
  "Google Sans",
  "Google Sans Yami",
  "Hack",
  "HarmonyOS Sans",
  "HarmonyOS Sans Condensed",
  "HeavyData Nerd Font",
  "HeavyData Nerd Font Propo",
  "Hermit",
  "Hermit BoldItalic",
  "IBM 3270",
  "IBM Plex Mono",
  "IEC symbols Unicode",
  "Impact",
  "Inconsolata",
  "Inconsolata LGC Nerd Font",
  "Inconsolata LGC Nerd Font Mono",
  "Inconsolata LGC Nerd Font Propo",
  "Inconsolata Nerd Font",
  "Inconsolata Nerd Font Mono",
  "Inconsolata Nerd Font Propo",
  "Inconsolata for Powerline",
  "Inconsolata for Powerline BoldForPowerline",
  "Inconsolata-dz for Powerline",
  "Inconsolata-g for Powerline",
  "InconsolataGo Nerd Font",
  "InconsolataGo Nerd Font Mono",
  "InconsolataGo Nerd Font Propo",
  "Ink Free",
  "Intel One Mono",
  "Inter",
  "Inter UI",
  "Inter Variable Text",
  "Iosevka",
  "Iosevka Nerd Font Propo",
  "IosevkaTerm Nerd Font",
  "IosevkaTermSlab Nerd Font",
  "IosevkaTermSlab Nerd Font Mono",
  "IosevkaTermSlab Nerd Font Propo",
  "IrisUPC",
  "Iskoola Pota",
  "JasmineUPC",
  "Javanese Text",
  "JetBrains Mono",
  "JetBrains Mono NL",
  "JetBrainsMono Nerd Font",
  "JetBrainsMono Nerd Font Mono",
  "JetBrainsMono Nerd Font Propo",
  "JetBrainsMonoNL Nerd Font",
  "JetBrainsMonoNL Nerd Font Mono",
  "JetBrainsMonoNL Nerd Font Propo",
  "JuliaMono",
  "KaiTi",
  "Kalinga",
  "Kartika",
  "Khmer UI",
  "KodchiangUPC",
  "Lao UI",
  "Latha",
  "Leelawadee",
  "Leelawadee UI",
  "Lekton Nerd Font",
  "Lekton Nerd Font Mono",
  "Lekton Nerd Font Propo",
  "Levenim MT",
  "Liberation Mono for Powerline",
  "Lilex",
  "Lilex Nerd Font",
  "Lilex Nerd Font Mono",
  "Lilex Nerd Font Propo",
  "Lilita One",
  "LilyUPC",
  "LiterationMono NF",
  "LiterationMono Nerd Font",
  "LiterationMono Nerd Font Mono",
  "LiterationMono Nerd Font Propo",
  "LiterationSans Nerd Font",
  "LiterationSans Nerd Font Propo",
  "LiterationSerif Nerd Font",
  "LiterationSerif Nerd Font Propo",
  "Lucida Console",
  "Lucida Sans Unicode",
  "Luculent 06",
  "Luculent 07",
  "Luculent 10",
  "Luculent 11",
  "M PLUS 1",
  "M PLUS 2",
  "M PLUS Code Latin 50",
  "M PLUS Code Latin 60",
  "M+1 Nerd Font",
  "M+1 Nerd Font Propo",
  "M+1Code Nerd Font",
  "M+1Code Nerd Font Mono",
  "M+1Code Nerd Font Propo",
  "M+2 Nerd Font",
  "M+2 Nerd Font Propo",
  "M+CodeLat50 Nerd Font",
  "M+CodeLat50 Nerd Font Mono",
  "M+CodeLat50 Nerd Font Propo",
  "M+CodeLat60 Nerd Font",
  "M+CodeLat60 Nerd Font Mono",
  "M+CodeLat60 Nerd Font Propo",
  "MS Gothic",
  "MS Mincho",
  "MS PGothic",
  "MS PMincho",
  "MS UI Gothic",
  "MV Boli",
  "Magnolia Script",
  "Malgun Gothic",
  "Maple Mono",
  "Maple Mono NF Base",
  "Maple Mono NF Base Mono",
  "Marlett",
  "Marta",
  "Martian Mono",
  "MartianMono Nerd Font",
  "MartianMono Nerd Font Mono",
  "MartianMono Nerd Font Propo",
  "Material Design Icons",
  "Material Design Icons Desktop",
  "Meiryo",
  "Meiryo UI",
  "Menlo",
  "Meslo LG L DZ for Powerline",
  "Meslo LG L for Powerline",
  "Meslo LG M DZ for Powerline",
  "Meslo LG M for Powerline",
  "Meslo LG S DZ for Powerline",
  "Meslo LG S for Powerline",
  "MesloLGL Nerd Font",
  "MesloLGL Nerd Font Mono",
  "MesloLGL Nerd Font Propo",
  "MesloLGLDZ Nerd Font",
  "MesloLGLDZ Nerd Font Mono",
  "MesloLGLDZ Nerd Font Propo",
  "MesloLGM Nerd Font",
  "MesloLGM Nerd Font Mono",
  "MesloLGM Nerd Font Propo",
  "MesloLGMDZ Nerd Font",
  "MesloLGMDZ Nerd Font Mono",
  "MesloLGMDZ Nerd Font Propo",
  "MesloLGS NF",
  "MesloLGS Nerd Font",
  "MesloLGS Nerd Font Mono",
  "MesloLGS Nerd Font Propo",
  "MesloLGSDZ Nerd Font",
  "MesloLGSDZ Nerd Font Mono",
  "MesloLGSDZ Nerd Font Propo",
  "Microsoft Himalaya",
  "Microsoft JhengHei",
  "Microsoft JhengHei UI",
  "Microsoft New Tai Lue",
  "Microsoft PhagsPa",
  "Microsoft Sans Serif",
  "Microsoft Tai Le",
  "Microsoft YaHei",
  "Microsoft YaHei Mono",
  "Microsoft YaHei UI",
  "Microsoft Yi Baiti",
  "MingLiU-ExtB",
  "MingLiU_HKSCS-ExtB",
  "MingLiU_MSCS-ExtB",
  "Miriam",
  "Miriam Fixed",
  "Modica Pro",
  "MonaspiceAr Nerd Font",
  "MonaspiceAr Nerd Font Mono",
  "MonaspiceAr Nerd Font Propo",
  "MonaspiceKr Nerd Font",
  "MonaspiceKr Nerd Font Mono",
  "MonaspiceKr Nerd Font Propo",
  "MonaspiceNe Nerd Font",
  "MonaspiceNe Nerd Font Mono",
  "MonaspiceNe Nerd Font Propo",
  "MonaspiceRn Nerd Font",
  "MonaspiceRn Nerd Font Mono",
  "MonaspiceRn Nerd Font Propo",
  "MonaspiceXe Nerd Font",
  "MonaspiceXe Nerd Font Mono",
  "MonaspiceXe Nerd Font Propo",
  "Mongolian Baiti",
  "Monofur Nerd Font",
  "Monofur Nerd Font Mono",
  "Monofur Nerd Font Propo",
  "Monoid Nerd Font",
  "Monoid Nerd Font Mono",
  "Monoid Nerd Font Propo",
  "Mononoki Nerd Font",
  "Mononoki Nerd Font Mono",
  "Mononoki Nerd Font Propo",
  "MoolBoran",
  "Multiround Pro",
  "Myanmar Text",
  "NSimSun",
  "Narkisim",
  "Neo Sans Pro Cyr",
  "Nerd Font File Types",
  "Neue Haas Grotesk Text Pro",
  "New York Extra Large",
  "Nirmala Text",
  "Nirmala UI",
  "Noto Mono",
  "Noto Mono for Powerline",
  "NotoMono Nerd Font",
  "NotoMono Nerd Font Mono",
  "NotoMono Nerd Font Propo",
  "NotoSans Nerd Font",
  "NotoSans Nerd Font Propo",
  "NotoSansM Nerd Font",
  "NotoSansM Nerd Font Mono",
  "NotoSansM Nerd Font Propo",
  "NotoSerif Nerd Font",
  "NotoSerif Nerd Font Propo",
  "NovaMono",
  "NovaMono for Powerline",
  "Nuqun",
  "Octicons Nerd Font",
  "Open Runde",
  "OpenDyslexic Nerd Font",
  "OpenDyslexic Nerd Font Propo",
  "OpenDyslexicAlt Nerd Font",
  "OpenDyslexicAlt Nerd Font Propo",
  "OpenDyslexicM Nerd Font",
  "OpenDyslexicM Nerd Font Mono",
  "OpenDyslexicM Nerd Font Propo",
  "OpenSans",
  "Ossem",
  "Ossem Rough",
  "Ossem Rounded",
  "Ossem Rust",
  "Overpass Mono",
  "Overpass Nerd Font",
  "Overpass Nerd Font Propo",
  "OverpassM Nerd Font",
  "OverpassM Nerd Font Mono",
  "OverpassM Nerd Font Propo",
  "Oxygen Mono",
  "PFBagueRoundPro ☞",
  "PFBagueRoundPro-BlackItalic ☞",
  "PFBagueRoundPro-BoldItalic ☞",
  "PFBagueRoundPro-LightItalic ☞",
  "PFBagueRoundPro-MediumItalic ☞",
  "PFBagueRoundPro-Regular ☞",
  "PFBagueRoundPro-ThinItalic ☞",
  "PFBagueRoundPro-UBlack ☞",
  "PFBagueRoundPro-UBlackItalic ☞",
  "PMingLiU-ExtB",
  "Palatino Linotype",
  "Plantagenet Cherokee",
  "Polly",
  "Polly Rounded",
  "Pomicons",
  "Ponter Rounded",
  "Powerline Extra Symbols",
  "PowerlineSymbols",
  "ProFont IIx Nerd Font",
  "ProFont IIx Nerd Font Mono",
  "ProFont IIx Nerd Font Propo",
  "ProFont for Powerline",
  "ProFontWindows Nerd Font",
  "ProFontWindows Nerd Font Mono",
  "ProFontWindows Nerd Font Propo",
  "ProggyClean CE Nerd Font",
  "ProggyClean CE Nerd Font Mono",
  "ProggyClean CE Nerd Font Propo",
  "ProggyClean Nerd Font",
  "ProggyClean Nerd Font Mono",
  "ProggyClean Nerd Font Propo",
  "ProggyCleanSZ Nerd Font",
  "ProggyCleanSZ Nerd Font Mono",
  "ProggyCleanSZ Nerd Font Propo",
  "Prosto One",
  "RF Dewi",
  "Raavi",
  "RecMonoCasual Nerd Font",
  "RecMonoCasual Nerd Font Mono",
  "RecMonoCasual Nerd Font Propo",
  "RecMonoDuotone Nerd Font",
  "RecMonoDuotone Nerd Font Mono",
  "RecMonoDuotone Nerd Font Propo",
  "RecMonoLinear Nerd Font",
  "RecMonoLinear Nerd Font Mono",
  "RecMonoLinear Nerd Font Propo",
  "RecMonoSmCasual Nerd Font",
  "RecMonoSmCasual Nerd Font Mono",
  "RecMonoSmCasual Nerd Font Propo",
  "Red Hat Mono",
  "Roboto",
  "Roboto Mono Light for Powerline",
  "Roboto Mono Medium for Powerline",
  "Roboto Mono Thin for Powerline",
  "Roboto Mono for Powerline",
  "RobotoMono Nerd Font",
  "RobotoMono Nerd Font Mono",
  "RobotoMono Nerd Font Propo",
  "Rockwell Nova",
  "Rod",
  "Rounded",
  "Rounded Mplus 1c",
  "RussianRail G Pro",
  "SF Mono",
  "SF Pro",
  "SF Pro - Soft",
  "SF Pro - Stencil",
  "SF Pro Display",
  "SF Pro Mistu Rounded",
  "SF Pro Rounded",
  "SF Pro Text",
  "SF UI Display",
  "SF UI Text",
  "Sans Serif Collection",
  "SauceCodePro Nerd Font",
  "SauceCodePro Nerd Font Mono",
  "SauceCodePro Nerd Font Propo",
  "Segoe Fluent Icons",
  "Segoe MDL2 Assets",
  "Segoe Print",
  "Segoe Script",
  "Segoe UI",
  "Segoe UI Emoji",
  "Segoe UI Historic",
  "Segoe UI Symbol",
  "Segoe UI Variable Display",
  "Segoe UI Variable Small",
  "Segoe UI Variable Text",
  "Shonar Bangla",
  "Shruti",
  "ShureTechMono Nerd Font",
  "ShureTechMono Nerd Font Mono",
  "ShureTechMono Nerd Font Propo",
  "SimHei",
  "SimSun",
  "SimSun-ExtB",
  "SimSun-ExtG",
  "Sitka Banner",
  "Sitka Display",
  "Sitka Heading",
  "Sitka Small",
  "Sitka Subheading",
  "Sitka Text",
  "Sofia Sans",
  "Sofia Sans BlackItalic",
  "Sofia Sans BoldItalic",
  "Sofia Sans ExtraBoldItalic",
  "Sofia Sans ExtraLightItalic",
  "Sofia Sans HairLine",
  "Sofia Sans HairLineItalic",
  "Sofia Sans HeavyItalic",
  "Sofia Sans LightItalic",
  "Sofia Sans MediumItalic",
  "Sofia Sans Pictograms",
  "Sofia Sans SemiBoldItalic",
  "Sofia Sans SemiLight",
  "Sofia Sans SemiLightItalic",
  "Sofia Sans ThinItalic",
  "Sofia Sans UltraLightItalic",
  "Source Code Pro",
  "Source Code Pro for Powerline",
  "Source Code Variable",
  "SourceCodeVF",
  "Space Mono",
  "Space Mono for Powerline",
  "SpaceMono Nerd Font",
  "SpaceMono Nerd Font Mono",
  "SpaceMono Nerd Font Propo",
  "Srbija Sans",
  "Stage Wander",
  "Sylfaen",
  "Symbol",
  "Symbol Neu for Powerline",
  "Symbols Nerd Font",
  "Symbols Nerd Font Mono",
  "TT Rounds Neue",
  "Tactic Round Bld",
  "Tactic Round Bld It",
  "Tactic Round Blk",
  "Tactic Round Blk It",
  "Tactic Round Exd Bld",
  "Tactic Round Exd Bld It",
  "Tactic Round Exd Blk",
  "Tactic Round Exd Blk It",
  "Tactic Round Exd Lgt",
  "Tactic Round Exd Lgt It",
  "Tactic Round Exd Med",
  "Tactic Round Exd Med It",
  "Tactic Round Exd Reg",
  "Tactic Round Exd Reg It",
  "Tactic Round Exd Thn",
  "Tactic Round Exd Thn It",
  "Tactic Round Exd Ult",
  "Tactic Round Exd Ult It",
  "Tactic Round Ext Exd Bld",
  "Tactic Round Ext Exd Bld It",
  "Tactic Round Ext Exd Blk",
  "Tactic Round Ext Exd Blk It",
  "Tactic Round Ext Exd Lgt",
  "Tactic Round Ext Exd Lgt It",
  "Tactic Round Ext Exd Med",
  "Tactic Round Ext Exd Med It",
  "Tactic Round Ext Exd Reg",
  "Tactic Round Ext Exd Reg It",
  "Tactic Round Ext Exd Thn",
  "Tactic Round Ext Exd Thn It",
  "Tactic Round Ext Exd Ult",
  "Tactic Round Ext Exd Ult It",
  "Tactic Round Lgt",
  "Tactic Round Lgt It",
  "Tactic Round Med",
  "Tactic Round Med It",
  "Tactic Round Reg",
  "Tactic Round Reg It",
  "Tactic Round Thn",
  "Tactic Round Thn It",
  "Tactic Round Ult",
  "Tactic Round Ult It",
  "Tahoma",
  "Terminess Nerd Font",
  "Terminess Nerd Font Mono",
  "Terminess Nerd Font Propo",
  "Times New Roman",
  "Tinos Nerd Font",
  "Tinos Nerd Font Propo",
  "Tinos for Powerline",
  "Trebuchet MS",
  "Tunga",
  "Twemoji Mozilla",
  "UD Digi Kyokasho N",
  "UD Digi Kyokasho NK",
  "UD Digi Kyokasho NP",
  "Ubuntu",
  "Ubuntu Light",
  "Ubuntu Mono",
  "Ubuntu Mono - Bront",
  "Ubuntu Mono derivative Powerline",
  "Ubuntu Nerd Font",
  "Ubuntu Nerd Font Propo",
  "UbuntuMono Nerd Font",
  "UbuntuMono Nerd Font Mono",
  "UbuntuMono Nerd Font Propo",
  "UbuntuSans Nerd Font",
  "UbuntuSans Nerd Font Propo",
  "UbuntuSansMono Nerd Font",
  "UbuntuSansMono Nerd Font Mono",
  "UbuntuSansMono Nerd Font Propo",
  "VAG Round Cyrillic",
  "VAG Rounded",
  "VAGRoundedLTCYR ☞",
  "Vag_Rounded CY [Rus by me]",
  "Vani",
  "Verdana",
  "Verdana Pro",
  "VictorMono Nerd Font",
  "VictorMono Nerd Font Mono",
  "VictorMono Nerd Font Propo",
  "Vijaya",
  "Visby Round CF",
  "Volte Rounded",
  "Vrinda",
  "Weather Icons",
  "Webdings",
  "Wingdings",
  "Yu Gothic",
  "Yu Gothic UI",
  "Yu Mincho",
  "ZedMono Nerd Font",
  "ZedMono Nerd Font Mono",
  "ZedMono Nerd Font Propo",
  "codicon",
  "font-awesome-extension",
  "font-logos",
  "icomoon",
  "monofur for Powerline",
  "saxMono",
];
